### ISSUE TITLE
ShopKeepers hooking broken

### ISSUE THREAD

**Issue by MrMaleficus** [DenizenScript/Depenizen-For-Bukkit#111] opened 2016-06-23 13:32 UTC
Hello,

I've this log when the server is shutting down:

```
[15:28:07] [pool-2079904-thread-1/INFO]: [0;35;1m [0;31;1mERROR! [0;37;1mInternal exception was thrown! [m
[15:28:07] [pool-2079904-thread-1/WARN]: java.lang.reflect.InvocationTargetException
[15:28:07] [pool-2079904-thread-1/WARN]: 	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.aufdemrand.denizen.objects.dEntity.getAttribute(dEntity.java:2451)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2121)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.core.DefinitionTags.definitionTag(DefinitionTags.java:78)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:28:07] [pool-2079904-thread-1/WARN]: Caused by: java.lang.NullPointerException
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.gnomeffinway.depenizen.objects.shopkeepers.ShopKeeper.isShopKeeper(ShopKeeper.java:50)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.gnomeffinway.depenizen.extensions.shopkeepers.ShopKeepersEntityExtension.<init>(ShopKeepersEntityExtension.java:27)
[15:28:07] [pool-2079904-thread-1/WARN]: 	at net.gnomeffinway.depenizen.extensions.shopkeepers.ShopKeepersEntityExtension.getFrom(ShopKeepersEntityExtension.java:21)
[15:28:07] [pool-2079904-thread-1/WARN]: 	... 17 more
[15:28:07] [pool-2079916-thread-1/INFO]: [0;35;1m [0;31;1mERROR! [0;37;1mInternal exception was thrown! [m
[15:28:07] [pool-2079916-thread-1/WARN]: java.lang.reflect.InvocationTargetException
[15:28:07] [pool-2079916-thread-1/WARN]: 	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.aufdemrand.denizen.objects.dEntity.getAttribute(dEntity.java:2451)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2121)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.core.DefinitionTags.definitionTag(DefinitionTags.java:78)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:28:07] [pool-2079916-thread-1/WARN]: Caused by: java.lang.NullPointerException
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.gnomeffinway.depenizen.objects.shopkeepers.ShopKeeper.isShopKeeper(ShopKeeper.java:50)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.gnomeffinway.depenizen.extensions.shopkeepers.ShopKeepersEntityExtension.<init>(ShopKeepersEntityExtension.java:27)
[15:28:07] [pool-2079916-thread-1/WARN]: 	at net.gnomeffinway.depenizen.extensions.shopkeepers.ShopKeepersEntityExtension.getFrom(ShopKeepersEntityExtension.java:21)
[15:28:07] [pool-2079916-thread-1/WARN]: 	... 17 more
```

The ShopKeeper version has been updated : http://dev.bukkit.org/bukkit-plugins/shopkeepers/

Thank you !
MM

**Comment by Morphan1** [comment] 2016-06-23 18:41
Try the latest build

**Comment by MrMaleficus** [comment] 2016-06-23 20:30
Still here

```
[22:27:42] [Server thread/INFO]: [Shopkeepers] Disabling Shopkeepers v1.76
[22:27:42] [Server thread/INFO]: [Denizen] Disabling Denizen v0.9.8-SNAPSHOT (build 594)
[22:27:42] [pool-4895-thread-1/INFO]: [0;35;1m [0;31;1mERROR! [0;37;1mInternal exception was thrown! [m
[22:27:42] [pool-4895-thread-1/WARN]: java.lang.reflect.InvocationTargetException
[22:27:42] [pool-4895-thread-1/WARN]: 	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
[22:27:42] [pool-4895-thread-1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.aufdemrand.denizencore.objects.properties.PropertyParser.getProperties(PropertyParser.java:87)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.aufdemrand.denizen.objects.dEntity.getAttribute(dEntity.java:2451)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.aufdemrand.denizen.objects.dPlayer.getAttribute(dPlayer.java:2121)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.core.DefinitionTags.definitionTag(DefinitionTags.java:78)
[22:27:42] [pool-4895-thread-1/WARN]: 	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
[22:27:42] [pool-4895-thread-1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.TagManager.fireEvent(TagManager.java:83)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.aufdemrand.denizencore.tags.TagManager$1.run(TagManager.java:258)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:27:42] [pool-4895-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:27:42] [pool-4895-thread-1/WARN]: Caused by: java.lang.NullPointerException
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.gnomeffinway.depenizen.objects.shopkeepers.ShopKeeper.isShopKeeper(ShopKeeper.java:50)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.gnomeffinway.depenizen.extensions.shopkeepers.ShopKeepersEntityExtension.<init>(ShopKeepersEntityExtension.java:27)
[22:27:42] [pool-4895-thread-1/WARN]: 	at net.gnomeffinway.depenizen.extensions.shopkeepers.ShopKeepersEntityExtension.getFrom(ShopKeepersEntityExtension.java:21)
[22:27:42] [pool-4895-thread-1/WARN]: 	... 17 more
[22:27:42] [Server thread/INFO]: [Denizen]  v0.9.8-SNAPSHOT (build 594) disabled.
```

**Comment by Morphan1** [comment] 2016-06-23 22:01
Do you perhaps have 2 Shopkeeper plugin .jar files in your plugins folder? I think the error is being caused by ShopkeepersPlugin.getInstance() being null, which shouldn't happen unless the plugin didn't load

**Comment by MrMaleficus** [comment] 2016-06-24 11:14
@Morphan1 Nop, i've only one ShopKeepers plugin, the latest version: 1.76

**Comment by Morphan1** [comment] 2016-09-30 05:11
This should be fixed in the newest build

**Closed by Morphan1** 2016-09-30 05:11 UTC
